import { normalizeJapaneseText } from './japaneseText'

/** スーパーの売り場に近い順 */
export const SHOPPING_CATEGORIES = [
  '野菜',
  '果物',
  '肉',
  '魚介',
  '卵・乳製品',
  '豆腐・大豆',
  '米・麺・パン',
  '乾物・缶詰',
  '調味料',
  'その他',
] as const

export type ShoppingCategory = (typeof SHOPPING_CATEGORIES)[number]

const CATEGORY_KEYWORDS: { category: ShoppingCategory; keywords: string[] }[] = [
  {
    category: '肉',
    keywords: [
      '鶏もも',
      '鶏むね',
      '鶏胸',
      '鶏ひき',
      '豚ひき',
      '豚バラ',
      '合い挽き',
      'ひき肉',
      '挽き肉',
      '鶏肉',
      '豚肉',
      '牛肉',
      'チキン',
      'ポーク',
      'ビーフ',
      'ベーコン',
      'ソーセージ',
      'ハム',
      'スパム',
      '手羽',
      '豚',
      '鶏',
      '牛',
      '肉',
    ],
  },
  {
    category: '魚介',
    keywords: [
      'サーモン',
      '鮭',
      'サバ',
      '鯖',
      'サンマ',
      'いわし',
      'イワシ',
      '白身魚',
      'あさり',
      'しらす',
      'アンチョビ',
      'エビ',
      'イカ',
      'タコ',
      'カニ',
      'ツナ',
      'ちくわ',
      '魚',
    ],
  },
  {
    category: '卵・乳製品',
    keywords: [
      'うずら',
      '卵',
      'たまご',
      'モッツァレラ',
      'チーズ',
      'バター',
      '牛乳',
      'ヨーグルト',
      'サワークリーム',
      '生クリーム',
    ],
  },
  {
    category: '調味料',
    keywords: [
      '豆板醤',
      'コチュジャン',
      'オリーブオイル',
      'ごま油',
      'ラー油',
      '揚げ油',
      'みりん',
      'めんつゆ',
      'ポン酢',
      'ケチャップ',
      'マヨネーズ',
      'ホワイトソース',
      'タルタル',
      'カレールー',
      'カレー粉',
      'コンソメ',
      '片栗粉',
      '小麦粉',
      'はちみつ',
      '花椒',
      '黒胡椒',
      'こしょう',
      '鷹の爪',
      '唐辛子',
      'クミン',
      'ターメリック',
      'スパイス',
      'だし',
      '醤油',
      '味噌',
      '酢',
      '塩',
      '砂糖',
      '酒',
      'ワイン',
      'ソース',
      'からし',
    ],
  },
  {
    category: '豆腐・大豆',
    keywords: ['厚揚げ', '豆腐', '納豆', 'こんにゃく', 'レンズ豆', '大豆', '豆'],
  },
  {
    category: '米・麺・パン',
    keywords: [
      'スパゲッティ',
      'マカロニ',
      'ラザニア',
      'ライスヌードル',
      'フォー麺',
      '中華麺',
      '焼きそば麺',
      'ラーメン',
      'うどん',
      'そば',
      'そうめん',
      'パスタ',
      'トルティーヤ',
      'トッポキ',
      'キヌア',
      '餃子の皮',
      '春巻きの皮',
      'ピザ生地',
      'ワンタン',
      'ご飯',
      'ごはん',
      'パン',
      '米',
    ],
  },
  {
    category: '乾物・缶詰',
    keywords: [
      'かつお節',
      'わかめ',
      'のり',
      'ごま',
      'ナッツ',
      'ピーナッツ',
      '松の実',
      'ココナッツミルク',
      '梅干し',
    ],
  },
  {
    category: '果物',
    keywords: ['レモン', 'ライム', 'パイン', 'りんご', 'バナナ', 'いちご', 'みかん', 'キウイ'],
  },
  {
    category: '野菜',
    keywords: [
      'ブロッコリー',
      'カリフラワー',
      'ほうれん草',
      'ズッキーニ',
      'パプリカ',
      'ピーマン',
      'キャベツ',
      'レタス',
      '白菜',
      '長ねぎ',
      'ねぎ',
      '玉ねぎ',
      'たまねぎ',
      'にんじん',
      '大根おろし',
      '大根',
      'じゃがいも',
      '里芋',
      'れんこん',
      'ごぼう',
      'なす',
      'トマト',
      'きゅうり',
      'もやし',
      'にら',
      'にんにく',
      '生姜',
      'しょうが',
      '大葉',
      '三つ葉',
      'バジル',
      'パセリ',
      'ディル',
      'ローズマリー',
      'レモングラス',
      'コリアンダー',
      'しいたけ',
      'きのこ',
      'たけのこ',
      'かぼちゃ',
      'オクラ',
      'アスパラ',
      'アボカド',
      'コーン',
      'キムチ',
      'dill',
    ],
  },
]

const NORMALIZED_KEYWORDS = CATEGORY_KEYWORDS.map((row) => ({
  category: row.category,
  keywords: row.keywords.map((keyword) => normalizeJapaneseText(keyword)),
}))

export function classifyIngredient(name: string): ShoppingCategory {
  const normalized = normalizeJapaneseText(name)
  if (!normalized) return 'その他'
  for (const row of NORMALIZED_KEYWORDS) {
    if (row.keywords.some((keyword) => keyword && normalized.includes(keyword))) {
      return row.category
    }
  }
  return 'その他'
}
